os: linux
language: python
python:
  - "3.7"
before_install:
  # install conda
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  # build conda recipe
  - conda build -c conda-forge --python=$TRAVIS_PYTHON_VERSION conda-recipe

before_script:
  # create test env
  - conda create -n test-environment -c conda-forge --use-local python=$TRAVIS_PYTHON_VERSION pytorch-3dunet
  - conda activate test-environment
  # install test dependencies
  - conda install pytest

script:
  - pytest