package:
  name: pytorch-3dunet
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  noarch: python
  entry_points:
    - predict3dunet = pytorch3dunet.predict:main
    - train3dunet = pytorch3dunet.train:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - torchvision
    - tensorboardx
    - h5py
    - scipy
    - scikit-image
    - scikit-learn
    - pyyaml
    - hdbscan
    - setuptools

test:
  imports:
    - pytorch3dunet
    - pytorch3dunet.unet3d
    - pytorch3dunet.augment
    - pytorch3dunet.datasets
  requires:
    - pytest
  run:
    - py.test

about:
  home: https://github.com/wolny/pytorch-3dunet
  license: MIT
