package:
  name: pytorch-3dunet
  version: 1.0.2

source:
  git_rev: v1.0.2
  git_url: https://github.com/wolny/pytorch-3dunet.git

build:
  entry_points:
    - predict3dunet = main.predict:main
    - train3dunet = main.train:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python 3.7
    - torchvision
    - tensorboardx
    - h5py
    - scipy
    - scikit-image
    - scikit-learn
    - pyyaml
    - hdbscan
    - setuptools

test:
  requires:
    - pytest
  run:
    - pytest tests/

about:
  home: https://github.com/wolny/pytorch-3dunet