package:
  name: pytorch-3dunet
  version: 1.0.1

source:
  git_rev: 84cd6bf3536fa8f199d3431c3f2b5a671be6c224 #v1.0.1
  git_url: https://github.com/wolny/pytorch-3dunet.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python 3.7
    - torchvision
    #- tensorboardx
    - h5py
    - scipy
    - scikit-image
    - scikit-learn
    - pyyaml
    - hdbscan
    - setuptools

test:
  requires:
    - pytest
  run:
    - pytest tests/

about:
  home: https://github.com/wolny/pytorch-3dunet