package:
  name: pytorch-3dunet
  version: 1.0.0

source:
  git_rev: v1.0.0
  git_url: https://github.com/hci-unihd/pytorch-3dunet.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python 3.7
    - torchvision
    - tensorboardx
    - h5py
    - scipy
    - scikit-image
    - scikit-learn
    - pyyaml
    - hdbscan
    - setuptools

test:
  requires:
    - pytest
  run:
    - pytest tests/

about:
  home: https://github.com/hci-unihd/pytorch-3dunet